### ISSUE TITLE
关于对比算法HCCF在不同数据集上的参数设置

### ISSUE THREAD

**Issue by love-searcher** [HKUDS/LightGCL#1]
您好，我想请教一下当前实验下，您在运行对比算法HCCF时，在各个数据集上分别是怎么设置的参数的呢？（我目前是在Gowalla数据集上运行，但是效果会差特别多）

**Comment by Rick-Cai** [comment]
你好，以下是我们使用的参数:
yelp - $\lambda_1$ = 1e-3, $\lambda_2$ = 1e-2, $\tau$ = 1, dropout = 0.5
gowalla - $\lambda_1$ = 1e-3, $\lambda_2$ = 1e-3, $\tau$ = 0.1
ml10m - $\lambda_1$ = 1e-5, $\lambda_2$ = 1e-2, $\tau$ = 0.3, dropout = 0
amazon - $\lambda_1$ = 1e-4, $\lambda_2$ = 1e-2, $\tau$ = 1, dropout = 0.5
tmall - $\lambda_1$ = 1e-3, $\lambda_2$ = 1e-3, $\tau$ = 1
其他未提及的参数则依照原文。
