### ISSUE TITLE
infoNCE

### ISSUE THREAD

**Issue by hunaghuohui** [HKUDS/LightGCL#11]
你好，我是一个小白，看的论文不多，问的问题可能会很幼稚，但是还是希望你能解答我的疑惑。我在大部分论文中看到的infoNCE所用的只有正样本，而负样本只用在rec任务的bpr损失中。而这篇论文代码的infoNCE中都用到了正负样本，我尝试将iid修改为pos，只用正样本，效果略微下降，但依旧表现良好。请问，这两种方法有什么区别吗，哪种方法好一点？

**Comment by Rick-Cai** [comment]
你好，感谢关注我们的工作。InfoNCE loss主要的作用在于将不同结点的embeddings在空间中相互推开（公式的分母部分），因此采集任意结点来参与InfoNCE loss都是可以的。使用BPR的正负样本只是因为它们是现成的采好的样本而已。因此，你可以选择使用正负样本，或者仅使用正样本，或者仅使用负样本，或者干脆重新采一批样本，都没问题。
