### ISSUE TITLE
The performance in the paper is lower than that the code does.

### ISSUE THREAD

**Issue by Du-danger** [HKUDS/LightGCL#12]
The performance in the paper is lower than that the code does. For example, on gowalla, the actual running is Recall@20: 0.2103 Ndcg@20: 0.1223 Recall@40: 0.2991 Ndcg@40: 0.1453; but the paper is low (Recall@20: 0.1578 Ndcg@20: 0.0935 Recall@40: 0.2245 Ndcg@40: 0.1108). Is the paper not updated ?

**Comment by newlei** [comment]
I also find the same problem. What is the reason for this?
