### ISSUE TITLE
How to visualize Embedding distributions

### ISSUE THREAD

**Issue by MeycL** [HKUDS/LightGCL#14]
Thank you for your wonderful work, I'm a newbie about recommendation, and I was reading your article "LIGHTGCL: SIMPLE YET EFFECTIVE GRAPH CONTRASTIVE LEARNING FOR RECOMMENDATION", and I saw this visualization below. (on top of your existing code in this repository)?
![image](https://github.com/HKUDS/LightGCL/assets/96134259/3235c422-bb7a-4943-9188-91ad916fc198)

**Comment by MeycL** [comment]
If you can but it is not convenient you can send your code to my email 2517795008@qq.com

**Comment by Rick-Cai** [comment]
Hi, thanks for reading our paper. This visualization was created by using the [T-SNE in the sciki-learn library](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html). It is rather easy to use, and you can directly call the API. Feel free to let us know if you still have difficulty with it.

**Comment by MeycL** [comment]
I don't feel like I'm getting started yet and not quite sure what to visualize as input with T-SNE.

**Comment by Rick-Cai** [comment]
This plot is visualizing the learned embeddings (feature vectors) in the embedding space. The T-SNE is an approach to visualize high dimension vectors in a 2-D plot. So the inputs to T-SNE is the final user and item embeddings after the model is trained (you may want to sample part of the users/items as there are too many).

**Comment by MeycL** [comment]
Thank you for your patient and detailed answers, and I look forward to your frequent work afterwards.

**Comment by Rick-Cai** [comment]
Thank you. Good luck on your explorations in recommendation.
