### ISSUE TITLE
BUG in svd_u,s,svd_v = torch.svd_lowrank(adj, q=svd_q)

### ISSUE THREAD

**Issue by ByronLaw1025** [HKUDS/LightGCL#15]
While implementing the code, it appeared an bug

torch._C._LinAlgError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnXgeqrf( handle, params, m, n, CUDA_R_32F, reinterpret_cast<void*>(A), lda, CUDA_R_32F, reinterpret_cast<void*>(tau), CUDA_R_32F, reinterpret_cast<void*>(bufferOnDevice), workspaceInBytesOnDevice, reinterpret_cast<void*>(bufferOnHost), workspaceInBytesOnHost, info)`. This error may appear if the input matrix contains NaN.

But we have no idea to fix it.

**Comment by Rick-Cai** [comment]
Hi, thanks for implementing our code. Although I am not sure about the bug you mentioned, the input matrix should not contain NaN. All inputs should be real valued, by natural sense. If your data contains NaN, you can try to fix these entries by filling in zeros or by other interpolation approaches.
