### ISSUE TITLE
关于矩阵normalize的问题

### ISSUE THREAD

**Issue by genemine** [HKUDS/LightGCL#16]
您好，我在复现您的代码的过程中发现了一个疑惑，就是您的原始邻接矩阵和SVD分解重构的矩阵都没有进行normalize操作，但您在原文中对原始邻接矩阵的卷积是做了normalize的，为何在实现的时候不加normalize呢？此外，如果不加normalize直接进行图消息传递的话可能会出现问题，为何文章中对SVD分解重构的矩阵不进行normalize再进行图消息传递呢？还有一个小问题，就是使用SVD分解重构之后矩阵中会出现负值，但代码中没有对负值进行处理，请问负值会对结果产生影响吗？

**Comment by Rick-Cai** [comment]
您好，感谢关注我们的工作。您发给我的邮件我已收到并回复，抱歉前几日没有上GitHub，回复较慢。我把邮件里的回复也贴在下面：

我们在提交原论文至iclr时，代码中原始邻接矩阵是有进行normalize的，而svd重构的确实是未经normalize的原图。后来我们也意识到svd重构normalized后的原图会更好，因此目前GitHub上的版本是有经过normalize的。这个版本是今年三月上传的，不知道您用的是不是这个最新的版本？

至于svd重构的矩阵中含有负值，我们并未发现这对模型训练有不良影响。事实上svd重构也是一种分析edge重要性的过程，被分配负值的edge很可能是一些不重要或不相关的edge。

**Comment by genemine** [comment]
非常感谢您的回复！
