### ISSUE TITLE
About the time complexity

### ISSUE THREAD

**Issue by SpaceLearner** [HKUDS/LightGCL#3]
Very nice work! While I find the time complexity I computed for graph convolution of LightGCL should be O[2ELd + 2IJLd] which is not aligned with that in the paper in Table 2. I think the reconstructed graph is fully connected (a dense matrix) and can not use sparse matrix multiplication to make acceleration. Can you help me figure it out? Thanks!

**Comment by Rick-Cai** [comment]
Thank you for your comment. You are right that the reconstructed graph is fully connected. However, please note that the reconstructed graph is actually the product of three low dimension matrices U,S,V', whose dimensions are I×q, q×q, q×J, respectively (where q is as small as 5). So we don't really need to compute the reconstructed graph, but just store the three low-dimension matrices. And by doing the matrix multiplication in the following order: US, V'E, and then (US)(V'E), we never need to construct that large matrix.

**Comment by mryjxu** [comment]
I wonder if this model can be used in scientific paper recommendation? Does it have a limited data set?
