### ISSUE TITLE
请问如何构建自己的数据集？谢谢！

### ISSUE THREAD

**Issue by fengxingxiang** [HKUDS/LightGCL#5]
请问如何构建自己的数据集？谢谢！

**Comment by Rick-Cai** [comment]
你好，我们使用的数据集格式是scipy.sparse.coo_matrix。其中rows为user id，cols为item id，data均为1（代表user和Item的交互），然后用pickle保存为.pkl格式。如果需要运行自己的数据集，可以将数据集处理为上述格式，即可直接输入模型。

**Comment by fengxingxiang** [comment]
谢谢
