### ISSUE TITLE
论文的SVD分解是否有意义

### ISSUE THREAD

**Issue by Shane953** [HKUDS/LightGCL#7]
经过消融实验发现删去SVD分解，与自身节点对比结果也是一样的，并且--lambda1的值为1e-7这么小，cl_loss是否真的有作用呢

**Comment by dongwu92** [comment]
楼主这个点我也在尝试，有降低但不多，但是复现效果一些数据集也有下降，所以初步可以判断SVD分解意义不明显，方便分享一下消融实验的代码吗？

**Comment by akaxlh** [comment]
你好，感谢对我们工作的关注！关于模型效果，您可使用我们最新的代码进行测试，在我们的实验中，SSL能带来较为显著的收敛速度和效果提升。

CL for CF这条research line早期代表工作<a href='https://arxiv.org/pdf/2010.10783.pdf'>SGL</a>的motivation，是通过自监督学习产生更多的监督信号，缓解协同过滤最根本的challenge。之后，基于不同数据增强方法的对比学习方法被提出，从不同角度产生自监督信号，如<a href='https://arxiv.org/pdf/2202.06200.pdf'>NCL</a>引入结构和语义相关性、<a href='https://arxiv.org/pdf/2204.12200.pdf'>HCCF</a>引入全局建模视角。一些工作，如<a href='https://arxiv.org/pdf/2112.08679.pdf'>SimGCL</a>，指出了之前工作中的随机augmentation方法常常带来效果下降，提出了基于embedding的随机augmentation方法。本篇工作<a href='https://arxiv.org/pdf/2302.08191.pdf'>LightGCL</a>于去年年中完成，起源于我们在探索中发现简单使用预训练的SVD方法，可以快速构建相当有效的对比学习样本。

在对这条research line的继续探索中，我们也发现在一般场景下，仅仅基于infoNCE函数对user-item embedding相似性进行广泛的minimization、并增强user-item之间的alignment力度，在正样本学习和负样本学习方面均表现出相对BPR loss的优势。我们针对性地设计了一种Contrastive Regularization (CR)，并已将其应用到我们关于CF Model Compression的最新工作<a href='https://arxiv.org/pdf/2303.08537.pdf'>SimRec</a>中，代码和数据集已公开。亦有一些近期工作（<a href='https://arxiv.org/pdf/2206.12811.pdf'>DirectAU</a>、<a href='https://arxiv.org/pdf/2209.02544.pdf'>XSimGCL</a>）从不同角度阐述了相似的发现。其中，我们在我们的<a href='https://github.com/HKUDS/SSLRec'>SSLRec</a>框架中探究了DirectAU与CR trick的优劣。两者分别使用欧式距离和内积作为embedding关系度量，但效果异曲同工。两种方法主要因全局推远和batch内推远的区别，而在不同数据集上各有优劣。

希望能给您带来一些启发，欢迎交流讨论。
