### ISSUE TITLE
在局部图依赖关系建模过程中每一层embedding计算的问题

### ISSUE THREAD

**Issue by WanliYoung** [HKUDS/LightGCL#8]
作者您好！在图卷积的过程中，您在论文中给出的公式是：z(u)i,l = σ(p(Ai,:)E(v)l-1)，e(u)i,l = z(u)i,l + e(u)i,l-1。
但是您的代码实现是：
# aggregate
self.E_u_list[layer] = self.Z_u_list[layer]
self.E_i_list[layer] = self.Z_i_list[layer]
请问这里是否存在出入呢？是否应该加上self.E_u_list[layer-1]呢？

**Comment by Rick-Cai** [comment]
你好，谢谢关注我们的工作！没错，我们将这篇文章提交给iclr时是有使用residual connection的，但是后续实验中发现不用residual connection效果更好，因此在目前最新的代码中去掉了这一部分。由于iclr的final revision deadline已经过了，我们会在后续的arxiv版本中更新。

**Comment by WanliYoung** [comment]
您好，感谢您的答复！因为我在实验过程中也发现按原论文使用residual connection效果更差，故此提问。
同时，在原论文当中对于cl loss的计算公式是计算了每一层的E、G embedding的对比学习损失，而代码实现当中只用了各层累加的E_norm、G_norm进行对比损失计算。不知道是否有这个出入呢？

**Comment by Rick-Cai** [comment]
是的，这也是后续实验时的微调，感谢指出！

**Comment by WanliYoung** [comment]
好的，感谢答复！
